### ISSUE TITLE
Le bouton "quitter" ne fonctionne pas

### ISSUE THREAD

**Issue by sletort** [gabeta/pointpointgame#1]
Si on presse le bouton quitter en cours de partie,  rien ne se passe.

Quitter en début de partie fait démarrer le jeu.

**Comment by gabeta** [comment]
Merci @sletort le jeu n'est pas parfaitement terminer. Et merci pour ta contribution

**Comment by gabeta** [comment]
https://github.com/AneyaInc/pointpointgame/pull/2
